package org.ecos.logic.thelastandroidexam2;

import java.util.ArrayList;
import java.util.List;

public class PersonajeCollection {
    public static List<Personaje> getDatos() {
        List<Personaje> personajes = new ArrayList<>();

        personajes.add(new Personaje(1, "Homer ", "Homer Jay Simpson", 39, "Masculino", "estadounidense", "Homer Jay Simpson (Homero J. Simpson en Hispanoamérica y Homer J. Simpson en España) es un personaje ficticio protagonista de la serie de televisión de dibujos animados Los Simpson. Es el padre de la familia protagonista y uno de los personajes centrales y más importantes de la serie. Fue creado por el dibujante Matt Groening e hizo su debut en televisión el 19 de abril de 1987,  en el corto Good Night del programa El show de Tracey Ullman. Su segundo nombre es un juego de palabras; durante muchas temporadas no se supo qué había detrás de la J hasta que en el capítulo «D'oh-in' In the Wind» descubre que su segundo nombre es Jay (nombre en inglés de la letra j); de este modo,  cuando Homer pronuncia en inglés su propio nombre,  no se distingue si da la letra inicial del segundo nombre o este al completo.", R.drawable.homer_simpson));
        personajes.add(new Personaje(2, "Bart", "Bartholomew «Bart» J. Simpson", 10, "Masculino", "estadounidense", "Bartholomew «Bart» J. Simpson2​3​ (Bartolomeo «Bart» J. Simpson en Hispanoamérica) es uno de los personajes ficticios protagonistas de la serie de televisión de dibujos animados Los Simpson. Bart tiene diez años y es el primogénito y único hijo varón de Homer y Marge Simpson. Es el hermano mayor de Lisa y Maggie", R.drawable.bart_simpson));
        personajes.add(new Personaje(4, "Marge", "Marjorie Jacqueline Simpson", 34, "Femenino", "estadounidense", "Marjorie Jacqueline Simpson más conocida como Marge Simpson es un personaje ficticio de la serie de televisión de dibujos animados Los Simpson. Es la esposa de Homer Simpson y madre de los tres hijos que ha tenido de este matrimonio: Bart,  Lisa y Maggie. Ella,  junto al resto de su familia,  conforman el elenco de personajes protagonistas de Los Simpson,  su presencia ha demostrado ser fundamental para mantener la familia unida.", R.drawable.marge_simpson));
        personajes.add(new Personaje(3, "Lisa", "Lisa Marie Simpson", 8, "Femenino", "estadounidense", "Lisa Marie Simpson3​ es un personaje de la serie de televisión de dibujos animados Los Simpson. Es la hija mediana de Homer y Marge Simpson y hermana de Bart y Maggie. Goza de notable protagonismo y complejidad en la serie. Lisa fue concebida por el caricaturista Matt Groening y debutó en la televisión el 19 de abril de 1987,  en el cortometraje de dibujos animados titulado Good Night del programa de variedades El show de Tracey Ullman. ", R.drawable.lisa_simpson));
        personajes.add(new Personaje(5, "Abraham", "Abraham «Abe» Jebediah Simpson", 83, "Masculino", "Estadounidense", "Abraham «Abe» Jebediah Simpson,  más conocido como el Abuelo,  es un personaje de ficción de la serie de televisión de dibujos animados Los Simpson. En ella,  es el padre de Homer Simpson,  el abuelo de sus hijos Bart,  Lisa y Maggie y el suegro de Marge. El abuelo fue diseñado tempranamente para la segunda temporada de los cortos emitidos para el show de Tracey Ullman y ya presentaba las características que acabaría desarrollando en la serie de emisión internacional. En la versión original este personaje está doblado por Dan Castellaneta,  mientras que en las versiones hispanohablantes varios actores de voz se le han puesto,  diferentes al mismo que dobla a Homer Simpson. En el número mil del Entertainment Weekly,  Abe Simpson fue seleccionado como el abuelo para la familia perfecta de televisión", R.drawable.abraham_simpson));
        personajes.add(new Personaje(6, "Maggie ", "Margaret Simpson", 1, "Femenino", "estadounidense", "Margaret Simpson,  conocida como Maggie Simpson,  es un personaje ficticio de la serie de televisión de dibujos animados Los Simpson. Es la tercera hija del matrimonio protagonista,  Homer y Marge Simpson,  y la más joven de ellos. Sus hermanos mayores son Bart y Lisa Simpson. Siempre se la ve succionando un chupete y cuando camina,  suele tropezar con el mono y cae de frente.", R.drawable.maggie_simpson));
        personajes.add(new Personaje(7, "Moe", "Maurice Lester Szyslak", 76, "Masculino", "Italiano-Neerlandés", "Maurice Lester Szyslak,  más conocido como Moe Szyslak,  es un personaje de ficción de la serie animada televisiva Los Simpson,  propietario de la Taberna de Moe. La voz original es de Hank Azaria, 1​ y apareció por primera vez en el episodio Simpsons Roasting on an Open Fire.2​ En Hispanoamérica es doblado por Jorge Ornelas, 3​ y en España es doblado por Juan Perucho.4​ Según aseguró en un capítulo es neerlandés,  a pesar de que en otro capítulo su niño interior le habla en italiano,  e incluso en otro capítulo afirmó ser medio armenio,  aun así nunca queda claro. El nombre del personaje es un homenaje a Norm de la serie Cheers.", R.drawable.moe_szyslak));
        personajes.add(new Personaje(8, "Apu", "Apu Nahasapeemapetilon", 37, "Masculino", "Indio", "Apu Nahasapeemapetilones un personaje ficticio 2​ de la serie de televisión Los Simpson. Es el administrador de una tienda en Springfield,  el Kwik-E-Mart (en España El Badulaque),  al cual recurren diariamente los Simpson para comprar sus víveres. Es un inmigrante de la India.", R.drawable.apu_nahasapeemapetilon));
        personajes.add(new Personaje(9, "Krabappel", "Edna Krabappel, ", 40, "Femenino", "Estadounidense", "Edna Krabappel,  desde 2012 Edna Flanders,  fue un personaje ficticio de la serie de televisión animada Los Simpson. Sus alumnos y a veces otros personajes la apodan,  según el doblaje español,  «Sita Carapápel» o simplemente «La Carapápel» y,  según el doblaje hispanoamericano,  la «Señorita Krabapple». ", R.drawable.edna_krabappel));
        personajes.add(new Personaje(10, "Willy", "William McDougal", 50, "Masculino", "Escocés", "William McDougal,  o Willy (también conocido como Willie el jardinero y Willie el escocés) es un personaje de ficción de la serie de televisión de dibujos animados Los Simpson. Es doblado por Dan Castellaneta en la versión inglesa y en España es doblado por Luis Marín. En Hispanoamérica estaba doblado hasta la decimoquinta temporada (incluida) por Alejandro Villeli,  actualmente reemplazado por Sebastián Llapur. y en temporada 25 en adelante fue doblado por Raymundo Armijo.", R.drawable.groundskeeper_willie));
        personajes.add(new Personaje(11, "Milhouse", "Milhouse Van Houten", 11, "Masculino", "estadounidense", "Milhouse Mussolini Van Houten es un personaje ficticio de la serie animada Los Simpson,  creado por Matt Groening. Es el mejor amigo de Bart Simpson,  cursan juntos cuarto grado en la Escuela Primaria de Springfield como alumno de la clase de la profesora Edna Krabappel. Tiene aspecto y comportamientos de nerd,  pero dista mucho de serlo. De hecho,  en una ocasión señaló que no era un nerd «porque los nerds son listos»", R.drawable.milhouse_van_houten));
        personajes.add(new Personaje(12, "Ralph", "Ralph Wiggum", 8, "Masculino", "estadounidense", "Ralph Wiggum (en Hispanoamérica: Rafa o Ralph Górgory) es un personaje de la serie animada Los Simpson,  creada por Matt Groening. Es doblado por Nancy Cartwright en la versión inglesa y en España está doblado por Chelo Vivares. En Hispanoamérica la voz es de Mayra Arellano,  en algunos capítulos posteriores por Laura Torres y a partir de la decimosexta temporada por Maggie Vera.", R.drawable.ralph_wiggum));
        personajes.add(new Personaje(13, "Martin", "Martin Prince", 10, "Masculino", "estadounidense", "Martin Prince es un personaje de ficción en la serie animada de Los Simpson. El personaje es doblado por Russi Taylor y en Hispanoamérica hasta la decimoquinta temporada (incluida) por Laura Torres,  actualmente reemplazada por Georgina Sánchez.", R.drawable.martin_prince));
        personajes.add(new Personaje(14, "Nelson", "Nelson Mandela Muntz", 11, "Masculino", "estadounidense/Danes", "Nelson Mandela Muntz (anteriormente llamado Nelson Ruffino o Nelson Motta,  en primeras temporadas en el doblaje hispanoamericano) es un personaje de la serie animada de televisión Los Simpson. Él es doblado en inglés por Nancy Cartwright y en Hispanoamérica,  la realizó por primera vez Benjamín Rivera,  poco después alternándose y finalmente sustituido por Sergio Bonilla,  quien luego fue reemplazado por Moisés Iván Mora,  Eduardo Garza,  Carlos Amador III,  Edson Matus,  y Hugo Núñez. En España está doblado por Laura Palacios aunque en las primeras temporadas fue sustituida por Chelo Vivares y Celia Ballester", R.drawable.nelson_muntz));
        personajes.add(new Personaje(15, "Jimbo", "Jimbo Jones", 14, "Masculino", "estadounidense", "Jimbo Jones (Cenobio Jimbo Rosso en Latinoamérica) es un personaje de la serie de dibujos animados Los Simpson; es uno de los peores chicos de la escuela primaria de Springfield. Amigo de Nelson Muntz,  realiza vandalismo junto a él. Se hace ver como una persona ruda,  pero llora viendo telenovelas con su madre y se acobarda cuando un adulto le planta cara. Lleva siempre un gorro de lana.", R.drawable.jimbo));
        personajes.add(new Personaje(16, "Kearney", "Kearney Zzyzwicz", 22, "Masculino", "estadounidense", "Kearney es el matón con el hábito de golpear con su puño su otra mano. Aunque aparenta ser solo unos años más grande que Bart,  puede conducir,  ha salido con la madre de Jimbo (él insiste en que ella inició la relación) y ha sido visto afeitándose,  además de fumando.", R.drawable.kearney_zzyzwicz));
        personajes.add(new Personaje(17, "Otto", "Otto Mann", 26, "Masculino", "estadounidense", "Otto Mann es un personaje ficticio de la serie de dibujos animados Los Simpson creada por Matt Groening. La voz en su idioma original es realizada por Harry Shearer.2​ En Hispanoamérica estaba doblado hasta la decimoquinta temporada (incluida) por Herman López,  reemplazado por Luis Alfonso Padilla hasta la vigesimotercera temporada,  cuando fue resustituido por Gerardo García. En España fue doblado por Claudio Serrano hasta la undécima temporada (incluida), 3​ y fue sustituido por Julio Sanchidrián hasta la fecha.", R.drawable.otto_mann));
        personajes.add(new Personaje(18, "Barney", "Barney Gumble", 40, "Masculino", "estadounidense", "Barnard «Barney» Gumble3​ (Barney Gómez en Hispanoamérica hasta la temporada 24) es un personaje ficticio de la serie de televisión de dibujos animados Los Simpson. Es el alcohólico de Springfield,  seguidor de lord Palmerston y uno de los mejores amigos del protagonista,  Homer Simpson. Decidió dejar de beber en el capítulo «Days of Wine and D'oh'ses»,  coescrito por Dan Castellaneta,  y se mantuvo sobrio durante varias temporadas. Barney eructa en forma casi continua,  producto de su copiosa ingesta de cerveza.", R.drawable.barney_gumble));
        personajes.add(new Personaje(19, "Lou", "Lou", 45, "Masculino", "estadounidense", "Lou es sargento de policía. Se ha mencionado que posiblemente tenga estudios universitarios. Fue el baterista de la banda Sadgasm . Lou es de los dos,  el que siempre corrige a Clancy Wiggum. Muy probablemente Lou y Wiggum sean amigos personales dada la forma amigable en que se tratan durante sus charlas personales. El nombre de Lou está basado en el nombre del jugador de béisbol Lou Whitaker.3​ Hank Azaria dijo que la voz de Lou está basada en la de Sylvester Stallone", R.drawable.lou));
        personajes.add(new Personaje(20, "Ned Flanders", "Nedward Flanders", 42, "Masculino", "estadounidense", "Nedward Flanders2​ más conocido como Ned es un personaje ficticio de la serie de televisión de dibujos animados Los Simpson. La voz original en inglés es de Harry Shearer. En Hispanoamérica hasta la decimoquinta temporada (incluida) estaba doblado por Agustín Sauret,  en algunos episodios de temporadas 14 y 15 por José García y fue reemplazado por Óscar Gómez. En España fue doblado por Rafael Alonso,  Sr. de la primera a la tercera temporada,  y actualmente está doblado por Carlos Del Pino desde la cuarta temporada.1​ El apellido «Flanders» está basado en una calle de Portland (ciudad donde creció Matt Groening) llamada NE Flanders St", R.drawable.ned_flanders));
        personajes.add(new Personaje(21, "Skinner", "Seymour Skinner", 67, "Masculino", "estadounidense", "Seymour Skinner (cuyo nombre original era Armin Tamzarian o Armin Skinner en Hispanoamérica,  Armando Barreda3​) es un personaje de la serie animada Los Simpson. Es doblado por Harry Shearer en la versión inglesa. En España fue doblado por Antonio Medina hasta la tercera temporada y posteriormente por José Padilla,  mientras que en Hispanoamérica es doblado actualmente por Gerardo Vásquez desde la decimosexta temporada,  aunque en las primeras temporadas fue doblado por Agustín Sauret (las primeras cuatro temporadas),  y después por José Luis Castañeda (temporadas 5-9) y Gabriel Pingarrón (temporadas 9-15). Su apellido en la serie se debe al psicólogo B.F. Skinner.", R.drawable.skinner));
        personajes.add(new Personaje(22, "señor Burns", "Charles Montgomery Burns", 75, "Masculino", "estadounidense", "Charles Montgomery Burns,  más conocido como el señor Burns o Monty Burns,  es un personaje ficticio recurrente de la serie de televisión de dibujos animados Los Simpson,  creada por Matt Groening.  Es el propietario de la Planta de energía nuclear de Springfield y por tanto jefe de Homer Simpson. Es atendido casi todo el tiempo por Waylon Smithers,  su leal y adulador ayudante,  asesor,  confidente y admirador secreto.  El señor Burns es el ciudadano más rico,  poderoso y anciano de Springfield; la revista Forbes calcula que su fortuna ronda los 16, 8 mil millones de dólares.4​ Suele usar su poder y riquezas para hacer lo que le place sin pensar en sus consecuencias y sin la intervención de las autoridades. Estas características han hecho que la revista Wizard lo considerara como el cuadragésimo quinto gran villano de todos los tiempos", R.drawable.montgomery_burns));
        personajes.add(new Personaje(23, "Smithers", "Waylon Smithers", 40, "Masculino", "estadounidense", "Waylon Smithers Jr. (en Hispanoamérica Wándulo Smithers en algunas temporadas,  luego Waylon Smithers Jr y en algunos episodios Cástulo Smithers,  Ufano Smithers o Acacio Smithers) es un personaje ficticio recurrente de la serie de televisión de dibujos animados Los Simpson. Es el ayudante y asistente personal de Montgomery Burns,  dueño de la Planta de energía nuclear de Springfield", R.drawable.waylon_smithers));
        personajes.add(new Personaje(24, "Santa's ", "Pequeño Ayudante de Santa Claus", 2, "Macho", "n/a", "Santa's Little Helper (conocido como Pequeño Ayudante de Santa Claus en España y Ayudante de Santa o Huesos en Hispanoamérica) es el perro de la familia Simpson en la serie de televisión de dibujos animados Los Simpson. En las primeras temporadas,  en la versión de España es nombrado Botones de santa. Es un galgo inglés marrón. En un capítulo se menciona que su cumpleaños es el mismo día que el de Homer. El actor de voz que lo interpreta es Dan Castellaneta. En otro capítulo Bart utiliza su nombre para solicitar una tarjeta de crédito. Aun cuando llenó la solicitud usando el nombre correcto y completo (Ayudante de Santa),  la tarjeta le fue otorgada bajo el nombre de Ayudanto do Santos.", R.drawable.santas_little_helper));
        personajes.add(new Personaje(25, "Krusty", "Krusty el payaso", 54, "Masculino", "estadounidense", "Herschel Shmoikel Pinkus Yerocham Krustofsky,  conocido como Krusty el payaso o el payaso Krusty, 2​ es un personaje de la serie de dibujos animados Los Simpson. Su voz original se la da Dan Castellaneta. En España fue doblado por Rafael Alonso,  Sr. en las dos primeras temporadas y a partir de la tercera por Abraham Aguilar,  y en Hispanoamérica por Mario Sauret solo en la primera temporada,  a partir de la segunda fue doblado por Tito Reséndiz hasta la temporada 15 y por Sebastián Llapur de la temporada 15 hasta la temporada 25 y Mauricio Pérez en la temporada 25 en adelante,  algunas veces sustituido por Armando Réndiz o César Soto. Es el payaso que presenta el programa de televisión favorito de los niños de Springfield,  localidad donde transcurre principalmente la serie.", R.drawable.krusty));
        personajes.add(new Personaje(26, "Actor secundario Bob", "Actor secundario Bob", 39, "Masculino", "estadounidense", "Bob es egresado de Yale,  se considera un genio,  es republicano y un presuntuoso refinado. Comenzó su carrera como ayudante en el programa de televisión de Krusty el payaso,  pero se cansó de los abusos de Krusty e intentó culparlo de asalto a mano armada en Krusty Gets Busted. Sin embargo,  el plan de Bob fue frustrado por Bart Simpson y fue enviado a prisión. Con su verdadera personalidad revelada,  Bob asumió el papel de genio criminal en la serie. En los episodios que lo tienen como protagonista,  Bob escapa de prisión y desarrolla un plan de venganza que es evitado por Bart y Lisa. Frecuentemente tales planes incluyen intentos de asesinato,  generalmente contra Bart o Krusty.", R.drawable.robert_terwilliger));

        return personajes;
    }

}
